apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-data-pvc
  namespace: kather-baksho
  labels:
    app.kubernetes.io/part-of: kather-baksho
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
  namespace: kather-baksho
  labels:
    app.kubernetes.io/part-of: kather-baksho
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: kather-baksho
  labels:
    app.kubernetes.io/part-of: kather-baksho
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-pvc
  namespace: kather-baksho
  labels:
    app.kubernetes.io/part-of: kather-baksho
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
