import { Request, Response } from 'express';
import PDFDocument from 'pdfkit';
import { ReportSummaryPayload } from '../types/invoice';

export const generateReportPDF = (req: Request, res: Response): void => {
  try {
    const payload: ReportSummaryPayload = req.body;

    if (!payload.title || typeof payload.totalRevenue !== 'number') {
      res.status(400).json({ error: 'title and totalRevenue are required' });
      return;
    }

    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `inline; filename="sales_report_${Date.now()}.pdf"`
    );
    res.setHeader('X-Generated-By', 'kather_baksho-worker-ts');

    doc.pipe(res);

    const primaryColor = '#1e3d29';
    const secondaryColor = '#2d6a4f';

    // Header bar
    doc.rect(0, 0, doc.page.width, 10).fill(primaryColor);

    doc
      .fillColor(primaryColor)
      .fontSize(20)
      .font('Helvetica-Bold')
      .text('KATHER BAKSHO — EXECUTIVE ANALYTICS', 50, 40)
      .fontSize(12)
      .font('Helvetica')
      .fillColor(secondaryColor)
      .text(payload.title, 50, 68)
      .fontSize(9)
      .fillColor('#666666')
      .text(`Report Window: ${payload.startDate || 'All Time'} to ${payload.endDate || 'Present'}`, 50, 84)
      .text(`Generated By: ${payload.generatedBy || 'Staff/Admin System'} | Timestamp: ${new Date().toISOString()}`, 50, 96);

    doc.moveTo(50, 115).lineTo(545, 115).strokeColor('#d8e2dc').lineWidth(1).stroke();

    // Summary Metric Cards
    doc
      .rect(50, 130, 235, 70)
      .fill('#f4f9f4');
    doc
      .rect(50, 130, 235, 70)
      .strokeColor('#b7e4c7')
      .stroke();

    doc
      .fillColor(secondaryColor)
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('TOTAL REVENUE', 65, 145)
      .fillColor(primaryColor)
      .fontSize(18)
      .text(`BDT ${payload.totalRevenue.toLocaleString()}`, 65, 165);

    doc
      .rect(310, 130, 235, 70)
      .fill('#f4f9f4');
    doc
      .rect(310, 130, 235, 70)
      .strokeColor('#b7e4c7')
      .stroke();

    doc
      .fillColor(secondaryColor)
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('PROCESSED ORDERS', 325, 145)
      .fillColor(primaryColor)
      .fontSize(18)
      .text(String(payload.totalOrders || 0), 325, 165);

    // Breakdown Table
    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .fillColor(primaryColor)
      .text('CATEGORY PERFORMANCE BREAKDOWN', 50, 225);

    const tableTop = 245;
    doc.rect(50, tableTop, 495, 20).fill('#e9f5ed');

    doc
      .fillColor(primaryColor)
      .fontSize(9)
      .font('Helvetica-Bold')
      .text('Category', 65, tableTop + 5)
      .text('Orders / Units', 280, tableTop + 5, { align: 'center', width: 100 })
      .text('Revenue (BDT)', 400, tableTop + 5, { align: 'right', width: 130 });

    let currentY = tableTop + 25;

    const breakdown = payload.categoryBreakdown || [];
    if (breakdown.length === 0) {
      doc
        .font('Helvetica')
        .fontSize(9)
        .fillColor('#777777')
        .text('No categorical breakdown provided.', 65, currentY);
      currentY += 20;
    } else {
      breakdown.forEach((item) => {
        doc
          .font('Helvetica')
          .fontSize(9)
          .fillColor('#333333')
          .text(item.category, 65, currentY)
          .text(String(item.count), 280, currentY, { align: 'center', width: 100 })
          .text(`BDT ${item.revenue.toLocaleString()}`, 400, currentY, { align: 'right', width: 130 });

        currentY += 20;
        doc.moveTo(50, currentY - 3).lineTo(545, currentY - 3).strokeColor('#eeeeee').lineWidth(0.5).stroke();
      });
    }

    doc
      .fontSize(8)
      .fillColor('#888888')
      .text('Report generated securely via Kather Baksho Node.js + TypeScript Microservice engine.', 50, 750, { align: 'center', width: 495 });

    doc.end();
  } catch (err: any) {
    console.error('[Worker-TS] Report Generation Error:', err);
    res.status(500).json({ error: 'Failed to generate report PDF', details: err.message });
  }
};
