groups:
  - name: jaeger_spm_rules
    interval: 5s
    rules:
      - record: calls
        expr: label_replace(label_replace(label_replace(label_replace(label_replace(http_requests_total{status=~"[45].."}, "service_name", "order-service", "job", ".*"), "operation", "$1", "path", "(.*)"), "span_name", "$1", "path", "(.*)"), "span_kind", "SPAN_KIND_SERVER", "job", ".*"), "status_code", "STATUS_CODE_ERROR", "job", ".*")
      - record: calls
        expr: label_replace(label_replace(label_replace(label_replace(label_replace(http_requests_total{status=~"[23].."}, "service_name", "order-service", "job", ".*"), "operation", "$1", "path", "(.*)"), "span_name", "$1", "path", "(.*)"), "span_kind", "SPAN_KIND_SERVER", "job", ".*"), "status_code", "STATUS_CODE_OK", "job", ".*")
      - record: duration_bucket
        expr: label_replace(label_replace(label_replace(http_request_duration_seconds_bucket * 1000, "service_name", "order-service", "job", ".*"), "operation", "$1", "path", "(.*)"), "span_kind", "SPAN_KIND_SERVER", "job", ".*")
      - record: duration_milliseconds_bucket
        expr: label_replace(label_replace(label_replace(http_request_duration_seconds_bucket * 1000, "service_name", "order-service", "job", ".*"), "operation", "$1", "path", "(.*)"), "span_kind", "SPAN_KIND_SERVER", "job", ".*")
      - record: calls_total
        expr: label_replace(label_replace(label_replace(label_replace(http_requests_total, "service_name", "order-service", "job", ".*"), "operation", "$1", "path", "(.*)"), "span_kind", "SPAN_KIND_SERVER", "job", ".*"), "status_code", "STATUS_CODE_OK", "job", ".*")
